### ISSUE TITLE
Secrets retrieval script not sourced when used with Java Buildpack

### ISSUE THREAD

**Issue by micahlee** [cyberark/cloudfoundry-conjur-buildpack#28]
The Conjur supply buildpack expects the final buildpack to copy the scripts from the buildpack's staging directory to the app droplet's `/home/vcap/profile.d/` directory.

This doesn't appear to work correctly when the Java Buildpack is the final buildpack for an application.

### Temporary Workaround
An application may workaround this issue by sourcing the script retrieval directly from their application using a `.profile` in the apps root directory:
```
. /home/vcap/deps/0/profile.d/0001_retrieve-secrets.sh
```
> NOTE: The `0` in the path above is the index of the `conjur_buildpack` in the buildpacks list. This example assumes the `conjur_buildpack` is first, but should be adjusted to match your specific manifest.

### References
- This appears to be a known issue in the Java Buildpack, and is not intended to be address in the current generation of the Java Buildpack: https://github.com/cloudfoundry/java-buildpack/issues/695#issuecomment-472151928
    > NOTE: The next generation of the buildpack contract (V3) will handle profile sourcing natively, and we'll not require the final buildpack to handle it.

**Comment by izgeri** [comment]
@micahlee can you add some notes here about the potential fixes for this? it would probably also be good to reference the relevant issue in the java buildpack repo.
