### ISSUE TITLE
Online Buildpack uses wrong golang version

### ISSUE THREAD

**Issue by micahlee** [cyberark/cloudfoundry-conjur-buildpack#39]
https://github.com/cyberark/cloudfoundry-conjur-buildpack/pull/38 updated the golang version for the buildpack to `1.12`, including a non-backward compatible API change for obtaining the home directory.

The online buildpack, however, is still installing go `1.11`.

It looks like this wasn't caught before because of a bug in the online buildpack integration test: https://github.com/cyberark/cloudfoundry-conjur-buildpack/blob/master/ci/features/integration.feature#L32

**Comment by izgeri** [comment]
@micahlee It would be good to update the guidelines for this in CONTRIBUTING.md - that's where I looked to find out where to update the go version, and this was missing there.
