### ISSUE TITLE
Buildpack doesn't reference `meta-buildpack` in the upload script

### ISSUE THREAD

**Issue by BradleyBoutcher** [cyberark/cloudfoundry-conjur-buildpack#78]
## Is your feature request related to a problem? Please describe.

In `./upload.sh`, we use the `meta-buildpack` name as the `POSITION` value for `cf create-buildpack`, where the parameters are  `cf create-buildpack BUILDPACK PATH POSITION [--enable|--disable]`.

## Describe the solution you would like

We should update our process to use supply build packs, as per the documentation here: https://github.com/cf-platform-eng/meta-buildpack.
```
NOTE: Meta-buildback is being deprecated
Changes to the core CloudFoundry lifecycle process are making it hard to guarantee on-going compatibility with meta-buildpack and decorators. Some of the use cases for decorators can now be solved by leveraging the new [supply buildpack](https://docs.cloudfoundry.org/buildpacks/understand-buildpacks.html#supply-script) functionality. Some examples can be found at the bottom of this page.

If you are using meta-buildpack today and need to find an alternative, or have a use case that would have been addressed by decorators, please open an issue on this repo and we are happy to help you look for the right way to accomplish your task.
```

**Comment by izgeri** [comment]
Just a note: we already updated the buildpack to a supply buildpack. What's left in this script is a relic of the pre-supply buildpack days, when we determined the order of the conjur buildpack by the order of the meta buildpack. This no longer needs to be the case, and we should probably use `99` for the `POSITION` of the buildpack in this command.

**Comment by izgeri** [comment]
@BradleyBoutcher I'm seeing here that I recommended we set the position to 99, which basically means to add this buildpack to the bottom

Instead we've set it to position 1, which is ahead of other buildpacks people will have installed. Is there any reason not to change this to 99, to append our buildpack to the end instead of making it number 1?
