### ISSUE TITLE
Undocumented hard requirement for language buildpack

### ISSUE THREAD

**Issue by whip113** [cyberark/cloudfoundry-conjur-buildpack#83]
## Summary
If you do not explicitly include the language build pack in your application manifest (because it's automatically included by PCF), the conjur build pack will not invoke. This hard requirement is not documented.

## Steps to Reproduce
In you application's manifest.yml, only include the conjur build pack
Stage your app
Observe that the conjur build pack does not get invoked
## Expected Results
Conjur build pack should be invoked
## Actual Results (including error logs, if applicable)
Conjur build pack is not invoked
## Reproducible
   * [*] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
cf cli version 6.51
DAP 11.5
PCF 2.9 (?)

**Comment by izgeri** [comment]
@whip113 would you suggest that we just add a bolded **Note** to [this section](https://github.com/cyberark/cloudfoundry-conjur-buildpack#invoke-the-installed-buildpack-at-deploy-time) to say something like:
> If you add the Conjur buildpack to your manifest or `cf push` command but don't also explicitly include the language buildpack, Cloud Foundry will see that the Conjur buildpack is not a "final buildpack" and will fail to invoke it. To use this buildpack, you **must** follow the instructions for [using multiple buildpacks](https://docs.cloudfoundry.org/buildpacks/use-multiple-buildpacks.html) and specify _both_ the Conjur buildpack **and** the final, language buildpack for your app (in that order).

**Comment by whip113** [comment]
I think that would be perfect.

**Comment by izgeri** [comment]
Resolved in #84
