### ISSUE TITLE
Buildpack has separate scripts for running unit and integration tests

### ISSUE THREAD

**Issue by izgeri** [cyberark/cloudfoundry-conjur-buildpack#94]
AC:
- [x] Buildpack has `bin/test_unit` for running unit tests and `bin/test_integration` for running lightweight integration tests
- [x] Any tests that run against a remote TAS instance are isolated into their own test scripts, with the goal of eventually keeping only smoke tests in this repo and running full end-to-end tests when we build the tile.

**Comment by doodlesbykumbi** [comment]
Fortunately the tests are already split up into unit and integration, see https://github.com/cyberark/cloudfoundry-conjur-buildpack/blob/master/Jenkinsfile#L32-L60.
```
    stage('Test') {
      parallel {
        stage('Integration Tests') {
          steps {
            sh 'summon ./test.sh'
            junit 'ci/features/reports/*.xml'
          }
        }

        stage('Unit Tests') {
          stages {
            stage("Secret Retrieval Script Tests") {
              steps {
                sh './ci/test-retrieve-secrets/start'
                junit 'TestReport-test.xml'
              }
            }

            stage("Conjur-Env Unit Tests") {
              steps {
                sh './ci/test-unit'
                junit 'conjur-env/output/*.xml'
              }
            }
          }
        }
      }
    }
  }
```

The desired split then mostly amounts to the following.

`./bin/test_unit`:
```
# Secret Retrieval Script Tests
../ci/test-retrieve-secrets/start

# Conjur-Env Unit Tests
../ci/test-unit'
```

`./bin/test_integration`:
```
# Integration tests
../test.sh
```

**Comment by BradleyBoutcher** [comment]
It's important to note that we cannot place any of our scripts within `bin`, as that is reserved for scripts that are actually ran by the buildpack when its installed.

**Comment by doodlesbykumbi** [comment]
@BradleyBoutcher thoughts on moving all buildpack source files into `./src` including the `bin` dedicated to the buildpack functionality ?

**Comment by BradleyBoutcher** [comment]
@doodlesbykumbi I'm in favor of the change, but I think we'd need to create a separate issue for it. It'd actually be fairly involved to change the directory structure for a few of these scripts, and we want to be sure we don't break any functionality.
